postgres:
  database: mea_db
  user: mea
  password: mea
  host: localhost
  port: 5432
  minsize: 1
  maxsize: 5


postgres_test:
  database: mea_db_test
  user: mea_test
  password: mea_test
  host: localhost
  port: 5432
  minsize: 1
  maxsize: 5
