"""Made usernme unique field in User table

Revision ID: 6fefb804d3cd
Revises: f0f4a2a70231
Create Date: 2021-08-08 21:11:50.899453

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '6fefb804d3cd'
down_revision = 'f0f4a2a70231'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_user_username', table_name='user')
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.create_index('ix_user_username', 'user', ['username'], unique=False)
    # ### end Alembic commands ###
