"""Added new field to Items table

Revision ID: f0f4a2a70231
Revises: 197e9334a034
Create Date: 2021-08-08 16:41:33.591014

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = 'f0f4a2a70231'
down_revision = '197e9334a034'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('item', sa.Column('name', sa.String(length=32), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('item', 'name')
    # ### end Alembic commands ###
